# Generated by Django 3.2.6 on 2021-08-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='Название услуги')),
                ('first_price', models.TextField(max_length=10, verbose_name='Цена 30 мин')),
                ('two_price', models.TextField(max_length=10, verbose_name='Цена 45 мин')),
                ('free', models.TextField(max_length=10, verbose_name='Цена 60 мин')),
                ('four_price', models.TextField(max_length=10, verbose_name='Цена 90 мин')),
            ],
            options={
                'verbose_name': 'Цены и услуга',
                'verbose_name_plural': 'Цены и услуги',
            },
        ),
    ]
