# Generated by Django 3.2.6 on 2021-08-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prices',
            old_name='free',
            new_name='free_price',
        ),
    ]
